name: Martha Made It
permalink: pretty
excerpt_separator: <!--more-->


product_groups:
- woman
- children

collections:
  product_types:
    output: true
  products:
    output: true
  fabrics:
  main-pages:
    output: true
    
    
    
    
defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
      _hide_content: true
  -
    scope:
      path: ""
      type: "product_types"
    values:
      layout: "products"
      _hide_content: true
      permalink: /:title/
      navclass:
  -
    scope:
      path: ""
      type: "fabrics"
    values:
      _hide_content: true